### ISSUE TITLE
ESX.TriggerServerCallback('otaku_vehicleshop:retrieveJobVehicles', function(jobVehicles)

### ISSUE THREAD

**Issue by PatientXero** [Sojobo/otaku_vehicleshop#9]
I followed the instructions, but this part of the script fails.

Running ESX Legacy 1.3 with up-to-date job files.

`[  script:es_extended] [WARNING] Server callback "otaku_vehicleshop:retrieveJobVehicles" does not exist. Please Check The Server File for Errors!
`

**Comment by PatientXero** [comment]
Found the fix in the config.lua. Sorry about that.

**Comment by 4EV3R** [comment]
How did you fix it? i need help
